FROM python:3.11-slim

WORKDIR /server

COPY requirements.txt /server/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /server/

CMD ["uvicorn", "server:application", "--host", "0.0.0.0", "--port", "9000"]
